### ISSUE TITLE
IOS apns notification not working

### ISSUE THREAD

**Issue by myoussef89** [matrix-org/sygnal#101]
I can receive notifications from android through firebase also I got this error which I don't know what is it related to:

Apr 09 22:02:44 ip-172-31-11-241 python3[29508]: Traceback (most recent call last):
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/.sygnal/lib/python3.6/site-packages/h2/connection.py", line 224, in process_input
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     func, target_state = self._transitions[(self.state, input_)]
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]: KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.SEND_HEADERS: 0>)
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]: During handling of the above exception, another exception occurred:
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]: Traceback (most recent call last):
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/sygnal/sygnal/http.py", line 234, in _handle_dispatch
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     result = await pushkin.dispatch_notification(notif, d, context)
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/sygnal/sygnal/apnspushkin.py", line 227, in dispatch_notification
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     log, span, device, shaved_payload, prio
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/sygnal/sygnal/apnspushkin.py", line 158, in _dispatch_request
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     response = await self._send_notification(request)
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/sygnal/sygnal/apnspushkin.py", line 418, in _send_notification
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     asyncio.ensure_future(self.apns_client.send_notification(request))
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/.sygnal/lib/python3.6/site-packages/twisted/internet/defer.py", line 824, in adapt
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     extracted = result.result()
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/.sygnal/lib/python3.6/site-packages/aioapns/client.py", line 49, in send_notification
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     response = await self.pool.send_notification(request)
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/.sygnal/lib/python3.6/site-packages/aioapns/connection.py", line 377, in send_notification
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     response = await connection.send_notification(request)
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/.sygnal/lib/python3.6/site-packages/aioapns/connection.py", line 176, in send_notification
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     headers=headers
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/.sygnal/lib/python3.6/site-packages/h2/connection.py", line 766, in send_headers
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     self.state_machine.process_input(ConnectionInputs.SEND_HEADERS)
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:   File "/home/ubuntu/.sygnal/lib/python3.6/site-packages/h2/connection.py", line 229, in process_input
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]:     "Invalid input %s in state %s" % (input_, old_state)
Apr 09 22:02:44 ip-172-31-11-241 python3[29508]: h2.exceptions.ProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

**Comment by richvdh** [comment]
please can you format the log so it is legible?

**Comment by myoussef89** [comment]
solved when I added development mode with the certificate
  com.xxxxx.xxxxxx.xxxxx.voip:
  type: apns
  platform: sandbox

Now I have to add 2 APNS certificate 1 for the VOIP and the other for the normal message

how can I do that? and I should use a different appID for each?
