### ISSUE TITLE
DeviceTokenNotForTopic

### ISSUE THREAD

**Issue by myoussef89** [matrix-org/sygnal#102]
cannot send VOIP push notification

Nots: the certificate is working fine from a dummy test service.

Apr 10 22:51:48 ip-172-31-11-241 python3[13121]: 2020-04-10 22:51:48,802 [13121] ERROR aioapns Status of notification 3af8357b-0673-497e-9546-384953672a1b is 400 (DeviceTokenNotForTopic)
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]: 2020-04-10 22:51:48,803 [13121] WARNING sygnal.http [e35a264c-eaf1-4985-ab64-26dc8c439ed2] Failed to dispatch notification.
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]: Traceback (most recent call last):
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]:   File "/home/ubuntu/sygnal/sygnal/http.py", line 234, in _handle_dispatch
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]:     result = await pushkin.dispatch_notification(notif, d, context)
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]:   File "/home/ubuntu/sygnal/sygnal/apnspushkin.py", line 227, in dispatch_notification
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]:     log, span, device, shaved_payload, prio
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]:   File "/home/ubuntu/sygnal/sygnal/apnspushkin.py", line 185, in _dispatch_request
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]:     f"{response.status} {response.description}"
Apr 10 22:51:48 ip-172-31-11-241 python3[13121]: sygnal.exceptions.NotificationDispatchException: 400 DeviceTokenNotForTopic

**Comment by clokep** [comment]
The error description from Apple doesn't give much more information:
> The device token does not match the specified topic.

But this sounds like the wrong token is being used or some other misconfiguration.

**Comment by clokep** [comment]
Also, you might want to check the #sygnal:matrix.org channel for troubleshooting.
