### ISSUE TITLE
[BUG] Problem with images

### ISSUE THREAD

**Issue by gperdomor** [matrix-org/sygnal#11]
In `apnpushkin.py` exist a series of four if-else-if blocks, but only can enter in the first two, this because the fallback in the top in the bottom image. This fallback code, set the `content_display = n.content["body"]` and the `else if is_image` and the last `else` is never reached.
<img width="584" alt="screen shot 2017-01-06 at 11 38 14 am" src="https://cloud.githubusercontent.com/assets/371939/21720961/b418a48c-d404-11e6-8b32-86294643bdf6.png">

So...

`IMAGE_FROM_USER_IN_ROOM`, `MSG_FROM_USER_IN_ROOM`, `IMAGE_FROM_USER`, MSG_FROM_USER` are never sended

**Comment by pbruna** [comment]
Just open a Pull Request to fix this: https://github.com/matrix-org/sygnal/pull/12/files

**Comment by richvdh** [comment]
assuming this is no longer a problem. Let us know if that is wrong.
