### ISSUE TITLE
service running  but not listening port 5000 

### ISSUE THREAD

**Issue by anilk9096** [matrix-org/sygnal#119]
OS VERSION : UBUNTU 16.04 LTS
PYTHON VERSION : Python 3.8.2
AWS HOSTING 

After running : python3.8 setup.py install (successful)
&
python3.8 -m sygnal.sygnal  : 
The following configuration fields are not understood: {'database'} 

 ps -def | grep sygnal
root      9689     1  0 09:20 ?        00:00:00 tcpdump -i any -w sygnal.pcap
root      9977  9953  1 10:45 pts/0    00:00:00 python3.8 -m sygnal.sygnal
root     10054 10038  0 10:45 pts/2    00:00:00 grep --color=auto sygnal

 netstat -pltun
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1246/sshd       
tcp6       0      0 :::22                   :::*                    LISTEN      1246/sshd       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           985/dhclient

**sygnal.log** : empty 

**syganl.yaml** 
attached sygnal.yaml kindly check 
[sygnal.zip](https://github.com/matrix-org/sygnal/files/4615467/sygnal.zip)

**Comment by babolivier** [comment]
So I've investigated this issue, and it looks like it's a combination of https://github.com/matrix-org/sygnal/issues/120 and a wrong configuration.

However, I can't process your config with this formatting to try to figure out what you might have misconfigured. Please surround your config sample with three backticks (```) to make it render as a code block, like this:

```
[...]
```

**Comment by anilk9096** [comment]
attached sygnal.yaml kindly review
[sygnal.zip](https://github.com/matrix-org/sygnal/files/4615470/sygnal.zip)

**Comment by babolivier** [comment]
Right, does `com.example.myApp_prod_APNS.pem` exist? If not, Sygnal will not be able to build the pushkins and soft-crash (because of #121).

**Comment by anilk9096** [comment]
Thank you @babolivier problem solved and service running
