### ISSUE TITLE
The sample logging configuration doesn't work

### ISSUE THREAD

**Issue by babolivier** [matrix-org/sygnal#120]
If used as is, the sample logging configuration makes Sygnal not log anything, neither in stdout, stderr nor sygnal.log.

When tweaking it to try to make it work somehow, I also couldn't get

https://github.com/matrix-org/sygnal/blob/9a1e3c8acddf8464e228b97aa2756f0bd3ba0848/sygnal/sygnal.py#L190-L192

or

https://github.com/matrix-org/sygnal/blob/9a1e3c8acddf8464e228b97aa2756f0bd3ba0848/sygnal/sygnal.py#L196-L196

or any log line that didn't originate from Twisted, to log, both in sygnal.log and in stderr.

**Comment by clokep** [comment]
I was able to get the output to go to stderr by adding `disable_existing_loggers: false` to the logging config. I'm unsure if that's the correct solution though.

**Comment by richvdh** [comment]
> I was able to get the output to go to stderr by adding disable_existing_loggers: false to the logging config. I'm unsure if that's the correct solution though.

normally it seems to be. I rather wish `disable_existing_loggers` was the default.
