### ISSUE TITLE
Make it clear that Sygnal is Element-flavoured, and document what other apps can expect

### ISSUE THREAD

**Issue by richvdh** [matrix-org/sygnal#128]
Although much of the framework of sygnal is valid as a reference push gateway, the pushkins are specific to riot-iOS/riot-X/riot-android, making the whole riot-specific.

A few things that would help make this clear:
 * updates in the readme to explain it
 * move the project to the vector-im github org
 * move the sygnal currently on matrix.org to riot.im

**Comment by reivilibre** [comment]
I don't see a reason that this should be Riot-specific as far as is feasible; it wouldn't stand if we turned around and said Synapse or Sydent were Riot-specific.

Of course, we have to apply some modest realism; it's likely out of scope to offer a completely customisable 'experience' without touching a line of code, yet on the other hand,
most IM-type apps will more or less want the same things and it seems only reasonable for us to support this kind of 'baseline' use-case by default.

Indeed, I didn't intentionally write anything to be Riot specific (though I may have missed some subtleties as I don't have *all* that much visibility into what happens on the target devices). There's not much to it in Sygnal; data comes from Synapse and Sygnal glues on an API key and rewrites it into GCM- or APNs-speke and bounces it off again.

If we shook out the last few drips (AFAICT) of Riot-specificism (#107), wouldn't Sygnal overall be better off?

**Comment by richvdh** [comment]
For the record, this issue came out of a discussion within the NV team (https://matrix.to/#/!WCHwNGGsrVwPeRtAnq:matrix.org/$1592306178253GDjUs:sw1v.org?via=sw1v.org&via=matrix.org&via=vector.modular.im, for those with access to it), where highlights include:

> [@dbkr] the apns pushkin is riot specific though

> [@richvdh] sure, but if half of sygnal is riot-specific, that must make the whole riot-specific

> [@dbkr] so yeah, technically vector-im may be a better place for it, or have syngnal in matrix-org and split out the riot pushkins into vector-im if you wanted to be really Technically Correct
> [@dbkr] (not that there are any other pushkins)

> [@dbkr] (to be clear, sygnal et al all date back from a time before riot or vector existed and Matrix Console roamed the lands which is why the water are so muddy here)

----

> (though I may have missed some subtleties as I don't have all that much visibility into what happens on the target devices)

I think this is kinda the trouble with making it generic: development is driven primarily by the riot mobile teams, meaning that bugs like #107 can exist for months without anyone noticing, and riot-specific behaviour gets introduced without it necessarily being clearly documented for other apps. (#127 was a recent example of this, although in that instance we eventually ended up with an implementation which seemed to be generic enough to make sense in its own right, and did get documented in the README).

Having mulled this over a bit in the last couple of weeks, I'm minded to agree with you that in principle there is no need for Sygnal itself or even the pushkins to be riot-specific (though the *instance* of sygnal which is deployed at `https://matrix.org/_matrix/push/v1/notify` necessarily *is*, because of the need for APNS/FCM account keys).

In practice it may be hard to come up with generic implementations of the pushkins which work for all apps, but I guess we should have a go.

**Comment by reivilibre** [comment]
Going to take this on as more of a documentation task

**Comment by reivilibre** [comment]
https://github.com/matrix-org/sygnal/issues/107#issuecomment-675423683 (default payload on iOS) could do with documentation as even I don't know where to look for nice, readable instructions of what to do
