### ISSUE TITLE
'MismatchSenderId': rejecting upstream

### ISSUE THREAD

**Issue by sagarkumars** [matrix-org/sygnal#147]
I am setting the pusher like this.

```
const serverUrl = `${homeServer}/_matrix/client/r0/pushers/set?access_token=${accessToken}`;
    const response = await axios.post(joinUrl, {
        "lang": "en",
        "kind": "http",
        "app_display_name": 'some name',
        "device_display_name": 'some name',
        "profile_tag": "xxyyzz",
        "app_id": "com.abc.info",
        "pushkey": '${SERVER_KEY}',
        "data": {
            "url": "http://${PUSH_GATEWAY}/_matrix/push/v1/notify",
            "format": "event_id_only"
        },
        "append": true
    });
```

when a user sends a message i get the error in logs

 Reg ID `SERVER_KEY` has permanently failed with code 'MismatchSenderId': rejecting upstream

Can you help me with this. TIA

**Comment by clokep** [comment]
It might be best to ask in #sygnal:matrix.org. Also, the logs aren't really readable, you probably want to use triple-ticks to format it.

**Comment by sagarkumars** [comment]
'''2020-08-12 19:17:49,307 [1] INFO  twisted Timing out client: IPv4Address(type='TCP', host='IP', port=41176)
2020-08-12 19:17:49,706 [1] INFO  sygnal.gcmpushkin [03d8f30d-fa39-48ec-bd29-8466d612b502] Sending (attempt 0) => ['A_n6_vk:APA91bGDVYSYlMajksdbjkcC6eJCvv8Cr9sQUWecADBncdi0NdHGJgahVDTxWMkfy-Yx_yMFy6gHz6CN1Q8dpw9-UQ80JXc1998A7XFyAbdsETnOfKPtJTbjCHILGFQP4V_tEeRzwCC0sAn']
2020-08-12 19:17:49,785 [1] WARNING sygnal.gcmpushkin [03d8f30d-fa39-48ec-bd29-8466d612b502] Error for pushkey A_n6_vk:APA9GDVmTYSYlMajksdbjkcC6eJCvv8Cr9sQUWecADBncdi0NdHGJgahVDTxWMkfy-Yx_yMFy6gHz6CN1Q8dpw9-UQ80JXc1998A7XFyAbdsETnOfKPtJTbjCHILGFQP4V_tEeRzwCC0sAn: MismatchSenderId
2020-08-12 19:17:49,786 [1] INFO  sygnal.gcmpushkin [03d8f30d-fa39-48ec-bd29-8466d612b502] Reg ID 'A_n6_vk:APA91bGDVYSYlMajksdbjkcC6eJCvv8Cr9sQUWecADBncdi0NdHGJgahVDTxWMkfy-Yx_yMFy6gHz6CN1Q8dpw9-UQ80JXc1998A7XFyAbdsETnOfKPtJTbjCHILGFQP4V_tEeRzwCC0sAn' has permanently failed with code 'MismatchSenderId': rejecting upstream
2020-08-12 19:17:49,786 [1] INFO  sygnal.http [03d8f30d-fa39-48ec-bd29-8466d612b502] Successfully delivered notifications with 1 rejected pushkeys
2020-08-12 19:17:49,787 [1] INFO  sygnal.access Handled request: "35.244.45.255" - - [12/Aug/2020:19:17:49 +0000] "POST /_matrix/push/v1/notify HTTP/1.1" 200 170 "-" "Synapse/1.17.0"
2020-08-12 19:18:49,789 [1] INFO  twisted Timing out client: IPv4Address(type='TCP', host='IP', port=41238)
2020-08-12 19:21:49,790 [1] INFO  twisted Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f1de24ad200>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f1de249cb90>)'''


Here is my log from Synapse

**Comment by reivilibre** [comment]
I believe that means that you need to ensure you have the correct api_key for that push token.

Also, it's worth checking the `google-services.json` file of your Android app is correct and corresponds to the same project in Firebase.

If you have checked both carefully, please reply back and we'll see what we can do.

**Comment by sagarkumars** [comment]
Thank you, It turns out i was sending the wrong Pusher Key. I made following changes

`const regId = await firebase.iid().getToken();`

```
const serverUrl = `${homeServer}/_matrix/client/r0/pushers/set?access_token=${accessToken}`;
    const response = await axios.post(joinUrl, {
        "lang": "en",
        "kind": "http",
        "app_display_name": 'some name',
        "device_display_name": 'some name',
        "profile_tag": "xxyyzz",
        "app_id": "com.abc.info",
        "pushkey": '${regId}',
        "data": {
            "url": "http://${PUSH_GATEWAY}/_matrix/push/v1/notify",
            "format": "event_id_only"
        },
        "append": true
    });
```

after this no longer getting the error i see following in log

```
2020-08-14 11:40:51,445 [1] INFO  sygnal.gcmpushkin [b92c5781-ad83-4e7d-a108-c84fb53353c9] Sending (attempt 0) => ['f2WojvXAQHKaz026EXop4u:APA91bE0lFNwPALRwD54TVmQUGPUQbOcpOWNPE_u6A31We8uq9C2UceClhz8q_pZoTBrgG0UHfBVcwkjNsRitSissYEpTi3edKeof9gkslFs1UfG_qMgqftMwZp8OeI4']
2020-08-14 11:40:51,551 [1] INFO  sygnal.access Handled request: "-" - - [14/Aug/2020:11:40:51 +0000] "POST /_matrix/push/v1/notify HTTP/1.1" 200 16 "-" "Synapse/1.17.0"
2020-08-14 11:41:51,553 [1] INFO  twisted Timing out client: IPv4Address(type='TCP', host='IP', port=55564)
2020-08-14 11:44:51,555 [1] INFO  twisted Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7fbf6447c8c0>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7fbf64429390>)
```

I don't receive any notification though. is there some other step i am missing here.

**Comment by reivilibre** [comment]
Are you writing your own app? If so, my guess would be that you are not handing data messages.

Sygnal does not send notification messages, so you won't see anything on your screen automatically. Your app will need to receive the data message and process it and display its own notification if it so wishes.

**Comment by sagarkumars** [comment]
I already have that in place. I can receive notifications i send from FCM server. 

Also how do i check if `sygnal`sent the notification to FCM server?

**Comment by reivilibre** [comment]
> FCM dashboard

The FCM dashboard sends notification (not data) messages.

> Also how do i check if sygnalsent the notification to FCM server?

A response code of 200 as in your above log suggests all is fine on that front.

**Comment by reivilibre** [comment]
Also, I haven't released this yet, but if you'd like to manually send an FCM message similar to what Sygnal might send, for testing, you can use this (which I have copied from a TROUBLESHOOTING.md document I am working on):

# Appendices

## Sending a notification to Sygnal manually with `curl`

Note: this depends on the heredoc syntax of the `bash` shell.

```bash
curl -i -H "Content-Type: application/json" --request POST -d '@-' http://syg1:8008/_matrix/push/v1/notify <<EOF
{
  "notification": {
    "event_id": "\$3957tyerfgewrf384",
    "room_id": "!slw48wfj34rtnrf:example.org",
    "type": "m.room.message",
    "sender": "@exampleuser:example.org",
    "sender_display_name": "Major Tom",
    "room_name": "Mission Control",
    "room_alias": "#exampleroom:example.org",
    "prio": "high",
    "content": {
      "msgtype": "m.text",
      "body": "I'm floating in a most peculiar way."
    },
    "counts": {
      "unread": 2,
      "missed_calls": 1
    },
    "devices": [
      {
        "app_id": "<APP ID HERE>",
        "pushkey": "<PUSHKEY HERE>",
        "pushkey_ts": 12345678,
        "data": {},
        "tweaks": {
          "sound": "bing"
        }
      }
    ]
  }
}
EOF
```


## Example of an FCM request

HTTP data sent to `https://fcm.googleapis.com/fcm/send`:

```
POST /fcm/send HTTP/1.1
User-Agent: sygnal
Content-Type: application/json
Authorization: key=<FCM TOKEN HERE>
Host: fcm.googleapis.com

{"data": {"event_id": "$3957tyerfgewrf384", "type": "m.room.message", "sender": "@exampleuser:example.org", "room_name": "Mission Control", "room_alias": "#exampleroom:example.org", "membership": null, "sender_display_name": "Major Tom", "content": {"msgtype": "m.text", "body": "I'm floating in a most peculiar way."}, "room_id": "!slw48wfj34rtnrf:example.org", "prio": "high", "unread": 2, "missed_calls": 1}, "priority": "high", "to": "<PUSHKEY HERE>"}
```

You can send using curl using: (please substitute in `<PUSHKEY HERE>` and `<FCM TOKEN HERE>`:

```bash
curl -i -H "Content-Type: application/json" -H "Authorization: key=<FCM TOKEN HERE>" --request POST -d '@-' https://fcm.googleapis.com/fcm/send <<EOF
{"data": {"event_id": "$3957tyerfgewrf384", "type": "m.room.message", "sender": "@exampleuser:example.org", "room_name": "Mission Control", "room_alias": "#exampleroom:example.org", "membership": null, "sender_display_name": "Major Tom", "content": {"msgtype": "m.text", "body": "I'm floating in a most peculiar way."}, "room_id": "!slw48wfj34rtnrf:example.org", "prio": "high", "unread": 2, "missed_calls": 1}, "priority": "high", "to": "<PUSHKEY HERE>"}
EOF
```

**Comment by sagarkumars** [comment]
Thanks got the message in data format. Is their any config i get them directly as notification. Also i see we only get messageId. do i have to make another API call to get message itself? TIA

```
{
  "data": {
    "event_id": "$G8OdbZUO82JQ7kpCHul7u_fsR7hYTdGhjU87kGJ1spU",
    "prio": "high",
    "room_id": "!LxxblGhVMBAmAtBHwI:",
    "unread": "0"
  },
  "from": "000000000000",
  "messageId": "0:1597497083126742%38b843b1f9fd7ecd",
  "sentTime": 1597497083112,
  "ttl": 2419200
}
```

**Comment by reivilibre** [comment]
No, sorry, there is no configuration option to get them as notification messages — there wouldn't be anything sensible to show for an encrypted message (you will need to download, decrypt and process these yourself, I'm afraid :C).

You do have the choice to get more information about the events, though.

`"format": "event_id_only"` will give you what you currently have, but you can also get more information if you don't specify that — see https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-pushers-set .

The downside of doing this is that Google will get this information as well, so consider it carefully first, as there are privacy implications :(.


Hope that helps.

**Comment by sagarkumars** [comment]
Thanks for the quick reply, I understand the limitation here, it would be great if notification feature could have been given as optional to user to integrate. Maybe as a configuration.  You can go ahead and close the issue. Thanks Again.

**Comment by reivilibre** [comment]
What would your hypothetical option do about encrypted messages though? :)

**Comment by sagarkumars** [comment]
Ahhh that makes sense. but i guess it should be left to the user to decide to get that notification message(Body) unencrypted. .  
BTW i am integrating this into a `react-native` mobile application so i need push notification, of course i can also do it with current messaging technique as well.

**Comment by reivilibre** [comment]
You're not necessarily wrong but adding that in would need someone to do it, and so far, apps have been left with the situation that event ID only format is obviously better for privacy, and they need the ability to download new events in the background anyway (as encrypted messages require this **before you can even display a notification** — because the event needs to be decrypted before we can decide if it should show a notification — the server can't help you with this), so event ID only is the easiest solution and the best for privacy.

In your mobile app, you should be able to run the event downloading code in a background process/task/thread (however it's called) — I'm not a react-native expert. But if you get stuck, I believe Ditto is a react-native mobile application and may contain some pointers for you?

**Comment by reivilibre** [comment]
Best of luck with that, I'm going to close this issue now as I think it is resolved, if you want help with your client then I am afraid that I am not your man (no experience with RN), but I do believe there are some places in the community you could go!
