### ISSUE TITLE
Issue with SSL Certificate Authority verification failure

### ISSUE THREAD

**Issue by AriBerisha** [matrix-org/sygnal#159]
I have a debian setup currently with matrix synapse and trying to get sygnal to work with push notifications on IOS,
Currently I have reverse proxies setup for both of them on nginx , in sygnal.yaml i have set up the app id and certfiles using p8 file such as :

apps:

  app_example:
    type: apns
    keyfile: authkey.p8
    key_id: 4NGUTGCNRY
    team_id: JUTVC5447J
    topic: app_example
    platform: (tried both sandbox and platform)

But i end up getting this
![IMAGE 2020-11-15 13_56_17](https://user-images.githubusercontent.com/50970388/99185777-5b700d80-274c-11eb-8db6-12fbbf019f5c.jpg)

Thank you in advance

**Comment by clokep** [comment]
Not directly an answer, but there is [some troubleshooting docs](https://github.com/matrix-org/sygnal/blob/master/docs/troubleshooting.md) that might be helpful (in particular they do talk about manually sending requests). There's also a #sygnal:matrix.org Matrix channel which might help.

It seems like this *might* be Fatal1ty/aioapns#20 though, the error message matches. I'd try the solution in there first.

**Comment by AriBerisha** [comment]
Finally got it working , for anyone else having problems do this:

Convert the CER file downloaded from app's APN (at developer.apple.com), to PEM
openssl x509 -in aps_development.cer -inform DER -out aps_development.pem -outform PEM

Convert the P12 file created with Keychain Access to PEM
openssl pkcs12 -nocerts -in Certificates.p12 -out Certificates.pem

Create a new, GOOD, P12 file
openssl pkcs12 -export -inkey Certificates.pem -in aps_development.pem -out GOOD_Certificates.p12


and then convert the .p12 file to pem. 

For some reason converting straight from .p12 provided by apple to pem did not work. This is the way to go

**Comment by clokep** [comment]
Glad you got it working! I'm going to close this for now.
