### ISSUE TITLE
VOIP Notifications (enhancement, not issue)

### ISSUE THREAD

**Issue by jorgevil92** [matrix-org/sygnal#16]
So, I installed sygnal a couple weeks back and it's working great. (had a couple issues with config, [I would suggest adding a 'platform' field to the sygnal.conf.sample file under the apns just for clarity] but nbd, it was all solved).
However, I'm trying to develop an iOS client that implements CallKit/PushKit notifications (aka VOIP Notifications) in order to improve the user experience and bring up the 'call' notifications without needing a background persistent connection.

Is anyone working towards adapting sygnal to these protocols? Can you think of any way to work around it? Should I be fine setting two pushers per iOS client (one for apns token and one for voip token) and then sending notifications through both (PushKit and regular UserNotifications)? Could I prevent double notifications by using some sort of pushrule to isolate voip/video calls?

Thank you!

**Comment by richvdh** [comment]
i think this issue is probably out of date.
