### ISSUE TITLE
Migrate GcmPushkin to FCM HTTP v1

### ISSUE THREAD

**Issue by kszzsk** [matrix-org/sygnal#162]
https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by reivilibre** [comment]
Is there a considerable advantage to migrating?

**Comment by kszzsk** [comment]
Being just up to date with external services essential for this project wouldn't be enough?

**Comment by reivilibre** [comment]
*If it isn't broken, don't fix it* might ring to mind. One day the time to migrate may come, but I doubt there is a big incentive at the moment... :)
