### ISSUE TITLE
Understand what the entries in gcm_canonical_reg_id table are used for

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/sygnal#165]
@jcgruenhage noticed that the table was empty on their deployment, and wondered what its purpose was.

Upon investigation, it appears that it's used as a mapping between "registration IDs" and "canonical registration IDs", where a "registration ID" is a pushkey, and a "canonical registration ID" (or [registration token](https://firebase.google.com/docs/cloud-messaging/concept-options#credentials)) is something we get back from FCM for identifying devices.

On matrix.org we have 20-30 entries in this table, which seems like quite a low number.

According to [this stackoverflow post](https://stackoverflow.com/questions/42930394/how-to-get-registration-ids-from-firebase-fcm) registration IDs can be used for various API calls - but it's still odd that there are so little of them saved, especially if they're per-device.

What are these things for?

**Comment by anoadragon453** [comment]
#sygnal:matrix.org discussion: https://matrix.to/#/!BmAgWlfcrgaRfViMVl:matrix.org/$1uCqppyXzvgYb98CgaVHBqKVKGYRRy3OVIh_oXA5BSw?via=matrix.org&via=vinix.im&via=amorgan.xyz

**Comment by reivilibre** [comment]
I think the canonical registration IDs are from an age gone by. (This Python 3 rewrite carried it over from before, and [a long time ago](https://github.com/matrix-org/sygnal/blob/f0585792effe6d01b2a4ad70ceaf975f667b0b91/sygnal/gcmpushkin.py#L29), we used GCM back when it was still called GCM).

https://stackoverflow.com/questions/48542261/retrieve-fcm-canonical-id-in-v1-api

We still use the 'Legacy' HTTP protocol, but I [still can't see any mention of 'canonical' in it](https://firebase.google.com/docs/cloud-messaging/http-server-ref).

It seems fairly clear we should be able to remove the database altogether; @H-Shay is doing just that.

**Comment by anoadragon453** [comment]
Very exciting - thanks for digging into it.
