### ISSUE TITLE
Ignore virtualenvs when running lints (flake8, black, etc) with tox

### ISSUE THREAD

**Issue by callahad** [matrix-org/sygnal#191]
Currently our CONTRIBUTING docs recommend creating a virtualenv in the same folder as Sygnal, but our tox.ini defaults to running linters over the current directory (e.g., `flake8 .`)... which then tries to apply the linter to _everything_ in the current directory, including your virtualenv.

We should probably edit tox.ini to only lint `sygnal/` `tests/` and `setup.py`

While we're at it, we should look into our `scripts-dev/lint.sh` and determine if that's used anywhere or if it's redundant with `tox`

**Comment by aitorres** [comment]
Hello! I would like to take on this issue and contribute with the project :-) 

Regarding the final remark, I think that running `tox -e check_codestyle` followed by `tox -e check_types` would be equivalent to running `scripts-dev/lint.sh`, so I would propose removing the shell script and replacing its use with both tox commands in CONTRIBUTING.md (and any other place it is mentioned).

**Comment by callahad** [comment]
Hi! Welcome!

> I would propose removing the shell script and replacing its use with both tox commands in CONTRIBUTING.md (and any other place it is mentioned).

Yes, I think so also :) Go for it.
