### ISSUE TITLE
Upgrade development dependencies

### ISSUE THREAD

**Issue by callahad** [matrix-org/sygnal#199]
Right now our [setup.py](https://github.com/matrix-org/sygnal/blob/ae797c739e13aca378e6de35d4a31e088cb619b7/setup.py#L57-L61) specifies exact versions of black, flake8, mypy, etc. We should update those to the latest versions and make sure the lints still pass.

It's probably easiest to do one commit per dependency, e.g.:

1. Update Black's version to [the latest](https://pypi.org/project/black/)
2. Run `tox --recreate` to pick up the new version of the library and see if anything is broken
3. Fix anything broken
4. Run `tox` to verify that everything is working
    (you don't need `--recreate` here since you already did that in step 2 above)
5. Commit your changes

**Comment by kibablu** [comment]
can I work on this @callahad

**Comment by clokep** [comment]
> correct me if I'm wrong, the packages needed to be updated are only in [extras_require](https://github.com/matrix-org/sygnal/blob/ae797c739e13aca378e6de35d4a31e088cb619b7/setup.py#L55)

This is correct.

I don't believe anyone is looking at this, so please give it a try! 👍

**Comment by kibablu** [comment]
Thank you, I'm working on it
