### ISSUE TITLE
Sygnal responds with 429, causing pushes to be lost

### ISSUE THREAD

**Issue by yoman88111** [matrix-org/sygnal#222]
### Description

We often encounter 429 errors when sending push events to matrix.org
The error in log shows
2021-04-23 11:41:21,430 - synapse.http.client - 444 - INFO - httppush.process-11407 - Received response to POST https://matrix.org/_matrix/push/v1/notify: 42
The problem mainly lasts from 8:00 to 10:00 UTC.
The problem is maybe related to high load on matrix servers. Any comments on this?

### Version information

- **Homeserver**: stadalone

- **Version**: 1.31.0

- **Install method**:
package manager

- **Platform**:
Debian 10.5

**Comment by richvdh** [comment]
Yes, it looks like the Sygnal instance is overloaded.

**Comment by callahad** [comment]
Context: The matrix.org haproxy is returning 429s on our end because it can't connect to our sygnal instance

There's probably a separate change that Synapse shouldn't drop pushes in response to a 429... but we also need to sort out why our Sygnal is overloaded

**Comment by richvdh** [comment]
we've improved things on the matrix.org server, and this looks better this morning. Thanks for the report.
