### ISSUE TITLE
Push calls do not reach, only on ios devices

### ISSUE THREAD

**Issue by QuickBanny** [matrix-org/sygnal#228]
We are having a problem with push notifications on ios devices when using apns.
"Fatal Exception: NSInternalInconsistencyException
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback."

We still cannot find addiction and what exactly is causing this crash. Sometimes the push kit works, sometimes the notifications about the call don't get through.

when the call goes through i see this logs message in sygnal

"Sending push to pushkin ru.bla.blatalk.voip for app ID ru.bla.blatalk.voip"

if it doesn’t work I don’t see such a message

it happens when the receiving device is inactive or active.

there are no messages in the synapse like ""Failed to push event""

**Comment by richvdh** [comment]
If the push is reaching sygnal, you should see entries like this in the sygnal logs:

```
2021-06-21 06:27:25,325 [20975] sygnal.access 344 - INFO - Handled request: "::ffff:10.103.0.1" - - [21/Jun/2021:06:27:25 +0000] "POST /_matrix/push/v1/notify HTTP/1.1" 200 16 "-" "Synapse/1.36.0"
```

Do you see entries like that corresponding to the notifications you expect?

**Comment by QuickBanny** [comment]
> If the push is reaching sygnal, you should see entries like this in the sygnal logs:
> 
> ```
> 2021-06-21 06:27:25,325 [20975] sygnal.access 344 - INFO - Handled request: "::ffff:10.103.0.1" - - [21/Jun/2021:06:27:25 +0000] "POST /_matrix/push/v1/notify HTTP/1.1" 200 16 "-" "Synapse/1.36.0"
> ```
> 
> Do you see entries like that corresponding to the notifications you expect?

Yes, the assumption that the voip is sent from the device to which the call is being made, and it is from the client that the push does not reach the signal

**Comment by richvdh** [comment]
> Yes, the assumption that the voip is sent from the device to which the call is being made, and it is from the client that the push does not reach the signal

I'm afraid I don't really understand this sentence. Please could you try to clarify?

**Comment by clokep** [comment]
Closing due to lack of response. Please let us know if you're still seeing this issue.
