### ISSUE TITLE
Not receiving VOIP Pushkit notifications in Background and terminated state in iOS app!

### ISSUE THREAD

**Issue by sourabhsharmait** [matrix-org/sygnal#235]
**Describe the bug**
We are trying to debug this issue for the last few weeks. We are not receiving any Pushkit notifications in the background & terminated state. 
We tried to restart the server but no luck. Yes but after restarting the server we receiving some  PushKit notifications in the background state but the success ratio was below 60%. 

VOIP Notifications are only appearing when user is online(MXPresenceOnline).
We are showing user online when app is in foreground state. And else we are showing offline.
<img width="1388" alt="Screenshot 2021-07-15 at 11 26 30 AM" src="https://user-images.githubusercontent.com/12099495/125736250-141b05ab-bee9-44ff-8712-8b318715cc65.png">

<img width="1367" alt="Screenshot 2021-07-15 at 11 25 42 AM" src="https://user-images.githubusercontent.com/12099495/125736178-e57a75e7-a063-450d-9ad2-f2b03a0d533f.png">

And I check the pushRegistry delegate methods. But the code is ok.
<img width="900" alt="Screenshot 2021-07-15 at 11 28 00 AM" src="https://user-images.githubusercontent.com/12099495/125736396-02eb95a9-8db3-4529-baa6-6f9119d1c60d.png">
<img width="1176" alt="Screenshot 2021-07-15 at 11 28 19 AM" src="https://user-images.githubusercontent.com/12099495/125736435-523348f6-1a32-4e27-a726-57cdb66f3ba7.png">
<img width="1426" alt="Screenshot 2021-07-15 at 11 28 39 AM" src="https://user-images.githubusercontent.com/12099495/125736466-8ea9d7a5-6dab-47b9-a68f-1ce325ad7636.png">

I checked the pem and VOIP certificate from the developer account but all are fine.

**To Reproduce**
It's weird but sometimes it works and sometimes it's not after restarting the Sygnal server. Some devices also receive calling notifications in the background and terminated state but sometimes they not. And some devices never receive Pushkit notifications in background.

**Comment by richvdh** [comment]
same as #228?

**Comment by sourabhsharmait** [comment]
no not same

**Comment by richvdh** [comment]
ok, please could you explain the difference?  I'm afraid I'm not that familiar with iOS development.

**Comment by sourabhsharmait** [comment]
We are having a problem with push notifications on ios devices when using apns.
"Fatal Exception: NSInternalInconsistencyException
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback."

We are not having any crash in our app but https://github.com/matrix-org/sygnal/issues/228 this thread is mentioned about that.

**Comment by erikjohnston** [comment]
As the exception says, when receiving a PushKit VoIP push the app *must* use CallKit to display a incoming call screen, if it doesn't then Apple will penalise the app by e.g. not giving it future push notifications.

This is a policy decided by Apple, so there's not anything Sygnal can do about it AFAIK, alas.

**Comment by manuroe** [comment]
To be complete on this: the push extension of the element-ios, gets all pushes via APNS. If we detect this is an event for an incoming call, this extension pings directly sygnal to send back a PK push. Thus, we can trigger CallKit and display a native incoming call.

Those restrictions came with iOS 13.
