### ISSUE TITLE
when is priority "normal" and when it is "high"?

### ISSUE THREAD

**Issue by Electrofenster** [matrix-org/sygnal#258]
Hey guys,

I want to know, when the priority for fcm notifications are "normal" and when they are "high".
In one room, I'll get the prio "normal" so no background notification could be started because the priority are to low.
In the others rooms the priority are "high". I could not figure out why the priority is normally "high" but in some cases are "normal".

The room notification settings are always "standard" on both rooms.

**Comment by Electrofenster** [comment]
@reivilibre for example:
1. user1 opens the app from app drawer/homescreen
2. user1 send some messages in an unencrypted room
3. user1 closes the app (on android) from recents apps, so the app is in quite state
4. user2 sends new messages on the unencrypted room

user1 didn't get an notification because the priority is "normal" so the app can't wake up the device from quite state because the priority ist not high enough. 

See: https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message -> high priority

**Comment by reivilibre** [comment]
I think this question has indeed been answered.
