### ISSUE TITLE
Issue in initial push notification in iOS with custom sygnal and matrix homeserver

### ISSUE THREAD

**Issue by arindampaul1993** [matrix-org/sygnal#272]
**Describe the bug**
The issue is happening on the latest sygnal release checked out from this github repository and matrix synapse checked out from the github repo of synapse. The issue is inconsistency in the banner display format of the push notification between the 1st and the consecutive iterations of any push notification , after installing our custom element app in iOS.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install element
2. Trigger push notification for a user
3. First notification comes up as "MESSAGE" without any info describing the push notification
4. All consecutive notifications after that show up fine.

**Expected behavior**
Expected behaviour is the notification banner should stay same throughout each push notification event.

**Smartphone (please complete the following information):**
 - Device: iPad Mini 5
 - OS: iOS
 - Version 14.6/15

**Comment by arindampaul1993** [comment]
?? is anyone looking into this?

**Comment by babolivier** [comment]
Hi, very sorry for the delay.

It looks like this is an issue with your custom fork of Element iOS (`MESSAGE` is referenced as a localisation key in the iOS app and isn't something returned by Sygnal). I'd hazard a guess that the NSX isn't set up properly.

Please open an issue on https://github.com/vector-im/element-ios as the Element iOS team would be better positioned to help you out.

**Comment by arindampaul1993** [comment]
sure, thanks for the input
