### ISSUE TITLE
Error Deserialize .p8 file 

### ISSUE THREAD

**Issue by MPTA** [matrix-org/sygnal#277]
i have installed sygnal by ansible ([ ](https://github.com/spantaleev/matrix-docker-ansible-deploy))

i used key authenticate and below config:

    com.noya.tel:
        key_id: YJ8YAZ9364
        keyfile: /data/push.p8
        team_id: 87234S9RTJ
        topic: 1592994573     /// appId
        type: apns

also uploaded p8 file in /matrix/sygnal/data folder

now i have this error: 

<img width="1270" alt="Screen Shot 1400-09-07 at 16 24 08" src="https://user-images.githubusercontent.com/40070445/143768776-9ca61063-096e-4805-8019-b12d349ef333.png">

**Comment by MPTA** [comment]
now after re generate .p8 file now i am getting this error, i really need help to config sygnal.
<img width="1471" alt="Screen Shot 1400-09-08 at 13 04 14" src="https://user-images.githubusercontent.com/40070445/143842964-f5b611e3-01d9-473a-af2d-37a7d14fc2c5.png">

**Comment by reivilibre** [comment]
Resolved out of band.

Issues were that the keyfile (p8) wasn't configured properly (should start `----- BEGIN PRIVATE KEY -----`) and the `topic` was not set properly (it was set to a number; should be textual and generally the same as the 'bundle identifier'). I will document these issues / add some more validation to try and stop people getting stuck in this quicksand in the future.
