### ISSUE TITLE
Python 3 Upgrade

### ISSUE THREAD

**Issue by abeluck** [matrix-org/sygnal#28]
Now that synapse supports python 3, what about sygnal?

Looking at the dependencies, flask supports python 3 on the currently pinned version. However  gevent (now pinned at 1.0.1) will need to be at least 1.1. pushbaby also needs an update, but this shouldn't be difficult as it only depends on gevent.

**Comment by abeluck** [comment]
I'd request that this issue be re-opened, as the PR from @evilham  doesn't make sygnal *fully* work on python 3.

Pushbaby is a dependency of sygnal, required for APNS notifications, and it does not work on python 3, therefore neither can sygnal.

**Comment by erikjohnston** [comment]
Ah, sure, it got closed automatically by merging the PR.

**Comment by reivilibre** [comment]
Addressed in #42
