### ISSUE TITLE
how to solve this problem builtins.TypeError: __init__() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by SyukurCode** [matrix-org/sygnal#298]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DMRobertson** [comment]
Sounds like https://github.com/matrix-org/sygnal/issues/293.

- How have you installed syngal?
- What version of syngal are you running?
- What version of `aioapns` is installed in your syngal environment?

**Comment by SyukurCode** [comment]
TQ it work now by install new pip package "aioapns==2.0.2",
