### ISSUE TITLE
can't run using docker

### ISSUE THREAD

**Issue by SyukurCode** [matrix-org/sygnal#299]
Hi, why i got this when run Dockerfile,

FileNotFoundError: [Errno 2] No such file or directory: 'sygnal.yaml' 

how to configure the directory for sygnal.yaml?

**Comment by squahtx** [comment]
You can use the `--volume` option to mount your sygnal config file inside the container.
eg. `sudo docker run --volume /full/path/to/sygnal/config.yaml:/sygnal.yaml matrixdotorg/sygnal`
