### ISSUE TITLE
Android, Apple and client cannot jump out the message.

### ISSUE THREAD

**Issue by rapking888** [matrix-org/sygnal#328]
I built the SYGNAL client by myself, but the Android, Apple and client cannot jump out the message. I have tried for a long time but still can't notify. What is the problem?

**Comment by DMRobertson** [comment]
We'd need more context (e.g. logs) to help you. Can you see requests being made to Sygnal in its logs? Can you see any errors in its logs?

Which client are you using to read these messages?

**Comment by H-Shay** [comment]
I am going to close this for now due to lack of activity, feel free to come back if you have logs/more info and we can re-open.
