### ISSUE TITLE
IOS ringtone in Matrix Synapse installed using ansible?

### ISSUE THREAD

**Issue by a19901201** [matrix-org/sygnal#329]
I have installed Matrix Synapse and Sygnal using this deployment script: https://github.com/spantaleev/matrix-docker-ansible-deploy but I am unable to figure out how to set the IOS ringtone.

I have tried the following configuration in the Sygnal configuration file, but it doesn't seem to work:
```

data:
  default_payload:
    aps
      sound:"ring.mp3"

data:
  default_payload:
    aps
      sound:"ring"

data:
  default_payload:
    aps:
      sound:"ring"

data:
  default_payload:
    aps:
      sound:"ring.mp3"

data:
  default_payload:
    aps:
      sound:ring.mp3

default_payload:["aps":["sound":"ring.mp3"]]

default_payload:["aps":{"sound":"ring.mp3"}]

default_payload:["aps":{"sound":"ring"}]

default_payload:["aps":["sound":"ring"]]

data:
  default_payload:
    aps:
      ["sound":"ring"]

data:
  default_payload:
    aps:
      {"sound":"ring"}

```

I have "Sounds/ring.mp3" in my APP
If you have any knowledge on how to resolve this issue, please help me out. Thank you!

**2023.02.13 update**
I have asked related questions multiple times in Sygnal repository, Sygnal and Matrix communities, but have never received any response. Only some people told me not to ask questions there and redirect me to other places. Each place asks me to go somewhere else to ask questions. Moreover, some other users even directly told me that asking questions in these places would not be helpful, and that I should try to solve problems myself. This has made me very frustrated. I have been building Matrix for more than six months, almost relying on try and error. I also hope to provide some amount of money to get paid help, but still without any results.

**2023.02.14 update**
The following SQL query was executed:
```
SELECT id,user_name,app_display_name,device_display_name,data 
FROM pushers 
WHERE kind='http' 
and user_name='@XXXXX02:sample.com';
```
And the result is:
```
 id  |         user_name          | app_display_name | device_display_name |                                          data
------+----------------------------+------------------+---------------------+----------------------------------------------------------------------------------------
 1086 | @XXXXX02:sample.com | im.XX.app        | VGOWCXPIXU          | {"url":"https://sygnal.sample.com/_matrix/push/v1/notify","format":"event_id_only"}
```
How to modify the notification sound?

**Comment by MatMaul** [comment]
There is no such thing as setting a ringtone at sygnal level. This is something that you should be able to do at the client level.
In Sygnal you only configure how to send push to your app, not what they will do with it, like playing a specific ringtone.

You can find examples of config in https://github.com/matrix-org/sygnal/blob/main/sygnal.yaml.sample.

**Comment by MatMaul** [comment]
Also if you don't plan to publish and use your own apps, you probably doesn't want to host Sygnal, as the push gateway is bounded to apps.

Please read https://spec.matrix.org/latest/push-gateway-api/ for more info on that.
