### ISSUE TITLE
support for FCM app type

### ISSUE THREAD

**Issue by dkinon** [matrix-org/sygnal#33]
GCM was deprecated a year ago (2018-04-10) and is set to be turned off this month:
https://developers.google.com/cloud-messaging/faq .  Is there an existing effort to support FCM on this or some other matrix project?

**Comment by t3chguy** [comment]
Seems like its already in use: https://github.com/matrix-org/sygnal/blob/678a2940017cb9b80a54582f12eeae9da7c5b765/sygnal/gcmpushkin.py#L32
