### ISSUE TITLE
missing setup.py file

### ISSUE THREAD

**Issue by Dabbit-Chan** [matrix-org/sygnal#339]
missing setup.py file, how to setup and load dependencies? thx.

**Comment by Dabbit-Chan** [comment]
> Related: #195

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /root/sygnal
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

**Comment by DMRobertson** [comment]
> > Related: #195
> 
> ```
> ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /root/sygnal
> (A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
> ```

How exactly did you generate this? Are you building the docker container? Are you installing sygnal from source? Something else?
