### ISSUE TITLE
Documentation for using Sygnal behind a reverse proxy

### ISSUE THREAD

**Issue by hmanzer** [matrix-org/sygnal#345]
I am looking at some guidance for running the sygnal server with https using caddy or any other reverse_proxy server

**Comment by hmanzer** [comment]
I am trying to use let's encrypt certificate (Caddy reverse proxy) same caddyfile as my matrix server but additional lines 

```
xx.xx.com{
  reverse_proxy /_matrix/v1/notify localhost:5000/
}
```

so our push gateway url in the client is `https://xx.xx.com/_matrix/v1/notify`
However the let's encrypt certificate doesn't work with push gateway but it works fine with matrix server.
If we remove push gateway from reverse proxy and directly hit with `http://staticip:5000/` the push notification reaches sygnal

Don't know why let's encrypt/reverse proxy isn't working for our push gateway configuration

**Comment by clokep** [comment]
>  However the let's encrypt certificate doesn't work with push gateway but it works fine with matrix server.

Can you expand more about what "doesn't work"? Are you getting an error somewhere? From the homeserver logs perhaps?

There should not be anything special about the reverse proxy for Sygnal, not that the URL is `/_matrix/push/v1/notify`, not `/_matrix//v1/notify`.

**Comment by clokep** [comment]
What are the sygnal logs? Do they show that a request comes in?

From the response I would *guess* that caddy is either responding directly *or* that it is sending it to the wrong process. Without showing more of your caddy file it is hard to know which it is.

**Comment by hmanzer** [comment]
There is nothing in sygnal logs when caddy/https is used. I saw that there is `200` code in matrix logs for pusher log which tells us that matrix is able to reach sygnal but the actual POST fails from matrix,  sygnal logs nothing (while using https). 

Caddyfile
```
zz.xx.com {
  reverse_proxy /_matrix/* localhost:8008
  reverse_proxy /_synapse/client/* localhost:8008
  reverse_proxy localhost:8008
}

xx.xx.com {
  reverse_proxy /_matrix/v1/notify localhost:5000/
}
server.xx.com:8448 {
  reverse_proxy localhost:8008
}
```
Where zz.xx.com is our main matrix URL and zz.xx.com is the pusher URL (sharing subdomain xx.com)
I have a thought that caddy is generating a let's encrypt certificate for zz.xx.com fine, I checked on browser, is there a conflict for xx.xx.com?.  Can pusher and matrix share same reverse proxy?

**Comment by clokep** [comment]
> Can pusher and matrix share same reverse proxy?

They should be able to. Are `zz` and `xx` different subdomains? (I'm wondering if there's any chance that the `/_matrix/*` is matching first as it encompasses `/_matrix/v1...`. I'm not sure how caddy resolves that.)

Note that again you've typed `/_matrix/v1/notify` instead of `/_matrix/push/v1/notify` -- this makes me very uncertain your config is correct.

**Comment by DMRobertson** [comment]
@hmanzer did you manage to get this working?

**Comment by hmanzer** [comment]
Yes. Thanks

Humayun Manzer
email: ***@***.***
