### ISSUE TITLE
anyway to use gcm/fcm key as of today 24/10/2023 for android notification

### ISSUE THREAD

**Issue by hmanzer** [matrix-org/sygnal#353]
We are trying to use gcm for android notification.
We have enabled `Cloud Messaging Legacy` and using the server key instead of api key but unable to get notification

```
 im.xxx.app:
    type: gcm
    api_key: <server key from legacy>
```

**Comment by rltas** [comment]
#313

**Comment by clokep** [comment]
I think this is a duplicate of #313, unfortunately there's no way to do this today as far as I know.
