### ISSUE TITLE
Sygnal.apnspushkin ERROR Error sending push to token

### ISSUE THREAD

**Issue by larry-troy** [matrix-org/sygnal#36]
Set up my local sygnal, uploaded pem certificate, 
send POST request to http: // localhost: 5000 / _matrix / push / v1 / notify, error in logs
pushbaby.pushconnection WARNING Push to tokenfailed with status 8
2019-05-06 11: 27: 52,208 k??ߗ??W?ǜ?~x?V??usF???5i?y{w???us?v?Ƶ???kG}, status 8
2019-05-06 11: 27: 52,215 pushbaby.pushconnection INFO Retrying 0 pushes sent after failed.
The token is correct and the certificate too, sent a request through curl and everything works, help please understand what the problem is.

**Comment by jonpennington** [comment]
I have a similar issue, did you find a solution?

**Comment by larry-troy** [comment]
No, I wrote my push gatway on the spring boot, if you want I can share it, do you want?

**Comment by jonpennington** [comment]
Oh cool that'd be great. Thanks!

**Comment by chokgithub** [comment]
I have same issue. got status 8 from apns

could you please check this issue

**Comment by brainahdev** [comment]
Yes I too have this issue.. even I double checked the certificate and both in dev and production the certificates are sending push If I try to send via php file..but when using in Sygnal I am getting the status code 8 error

**Comment by mrtshoot** [comment]
@larry-troy hi can you share with me your push gateway?
**thanks a lot**

**Comment by richvdh** [comment]
this code has been rewritten; assuming this issue is out of date.
