### ISSUE TITLE
FCM API Credential refresh mechanism doesn't support HTTP proxies and blocks the event loop

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/sygnal#371]
title says it all: it doesn't look like we support HTTP proxies here and given no `await` I suspect this also blocks the event loop:
https://github.com/matrix-org/sygnal/blob/c025ac1b16b347e31ae6c54d491c01c16b0de599/sygnal/gcmpushkin.py#L480

**Comment by reivilibre** [comment]
aiohttp supports proxies: https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support

as does HTTPX, which sounds like it could be the next big thing in Python, or maybe that's just some inflated hype — would need consideration: https://www.python-httpx.org/

**Comment by MatMaul** [comment]
The google-auth lib seems to support a custom `urllib3` pool: https://googleapis.dev/python/google-auth/latest/user-guide.html#urllib3

To my understanding we can replace an urllib3 `PoolManager` by a `ProxyManager`: https://urllib3.readthedocs.io/en/stable/advanced-usage.html#proxies

I guess it would be the straightest way to support a proxy here, what do you think ?

**Comment by MatMaul** [comment]
Oh urllib3 is blocking, but it seems we are using the `requests` backend for now, which is also blocking, hence the fact that there is no `await` I think.

We can also customize the requests `Session`, and use a proxy there: https://docs.python-requests.org/en/latest/user/advanced/#proxies

**Comment by MatMaul** [comment]
To be clear so we don't double the work, we need proxy support on our deploy so I am currently working on that, I should be able to send a PR this week.
