### ISSUE TITLE
Pushed data should contain the userId

### ISSUE THREAD

**Issue by bmarty** [matrix-org/sygnal#70]
In order to support multi accounts on matrix clients, the Push data which are sent to mobile Matrix clients should also contain the **user_id**, to let the app perform a sync on the correct account.

Related issue:
- https://github.com/vector-im/riotX-android/issues/26

**Comment by reivilibre** [comment]
This is going to require a spec change and it's not clear how it should work with e.g. the `event_id_only` format.

As a workaround, you could set up the pusher with a custom data attribute [(1)] which will be sent back to your client [(2)]

[1]: https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-pushers-set

[2]: https://matrix.org/docs/spec/push_gateway/r0.1.1#post-matrix-push-v1-notify

so you can sort of 'implement it yourself' in the meantime...

**Comment by bmarty** [comment]
@reivilibre I've done some test following your suggestion:
I can add more data to the PusherData when configuring the pusher, and then they are probably sent to Sygnal when the homeserver want to send a push, but I do not see those extra data on the Push content I actually receive on the mobile device.

**Comment by clokep** [comment]
Looking through Sygnal it seems that only a magic "default_payload" property of the data is actually sent:

https://github.com/matrix-org/sygnal/blob/53015c70785dea441606d1504667d71c5b99eabc/sygnal/gcmpushkin.py#L430-L431

**Comment by bmarty** [comment]
Ok, it works, thanks @clokep ! Element Android will use this trick to prepare multi account support.

**Comment by varac** [comment]
@bmarty Nice -  What's the status of multiple accounts on Element Android ?

**Comment by bmarty** [comment]
@varac it's still not planned yet, we're focusing on other features right now

**Comment by DraconicNEO** [comment]
I hope this gets implemented soon, so we'll be able to have multiple accounts

**Comment by reivilibre** [comment]
> I hope this gets implemented soon, so we'll be able to have multiple accounts

Is there a problem with the workaround described above that doesn't work for you?

**Comment by DraconicNEO** [comment]
> > I hope this gets implemented soon, so we'll be able to have multiple accounts
> 
> Is there a problem with the workaround described above that doesn't work for you?

Oh sorry, I don't think so, I just read that one of the reasons multiple account support wasn't implemented yet was because of this and since this issue is still open it seems like it hasn't yet been done. Sorry if I caused confusion.

**Comment by clokep** [comment]
I think we an close this. 😄

**Comment by jittygitty** [comment]
@bmarty For us new guys not as familiar with internals, how exactly can we "implement this ourselves" as @reivilibre said?
"As a workaround, you could set up the pusher with a custom data attribute [(1)](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-pushers-set) which will be sent back to your client [(2)](https://matrix.org/docs/spec/push_gateway/r0.1.1#post-matrix-push-v1-notify)"
thx!

**Comment by reivilibre** [comment]
@jittygitty Sorry for not seeing this sooner.

One of your clients can add this into the data attribute
`"default_payload":{"my_user_id":"@reivilibre:librepush.net"}`
(`"my_user_id":"@reivilibre:librepush.net"` will then come down in all the push messages for that account).

Another client could set
`"default_payload":{"my_user_id":"@my_other_account:librepush.net"}`

Then your client has something it can read when it receives a push, to determine which account the push is for.
