### ISSUE TITLE
Troubleshoot running Sygnal locally

### ISSUE THREAD

**Issue by scottwestover** [matrix-org/sygnal#75]
I am trying to run the Sygnal Push Gateway service locally, however I am running into an issue. After I install the required packages, and I start the service I am not seeing any output in the terminal. I am also not seeing any output being added to the `sygnal.log` file.

I tried visiting the Prometheus client on `http://localhost:8000/`, and I also tried sending a POST request to `http://localhost:5000/_matrix/push/v1/notify`, but I am still not seeing any logs and I am not getting a response from the service at all.

After cloning the repository, these are the command that I ran:
```
cp ./sygnal.yaml.sample ./sygnal.yaml
virtualenv env
source env/bin/activate
pip install .
```

My Python version: `Python 3.7.1`

Is there anything else I need to do to just get the service up and running? Or, do you have any tips for troubleshooting the issue? Any help would be much appreciated.

**Comment by chungggg** [comment]
Same with me, I don't how to run server. I tried with 'python -m sygnal.sygnal' but not work

**Comment by chungggg** [comment]
Edit: I forgot config apns in sygnal.yaml, after I edit sygnal.yaml sygnal server is worked with 'python -m sygnal.sygnal'

**Comment by scottwestover** [comment]
@chungggg Can you please share an example of what your `apps` section looks like in the config? I am trying to get the `apns` part to work, but it won't work locally with the provided `sygnal.yaml.sample`. 

However, if I enable the `gcm` app the service will start correctly.

**Comment by scottwestover** [comment]
I figured out my issue. If you try to import `aioapns` with python 3.7.5, the module will fail to load. I went ahead and upgraded my Python version to 3.7.5 and I am able to load the module correctly now.

Here is a link to the relevant issue in the `aioapns` package: https://github.com/Fatal1ty/aioapns/issues/9
