### ISSUE TITLE
APNS config warning on valid keys

### ISSUE THREAD

**Issue by jaywink** [matrix-org/sygnal#81]
When configuring an APNS via `keyfile`, sygnal warns about not understood config items:

```
2020-02-13 12:21:36,725 [1] WARNING sygnal.apnspushkin The following configuration fields are not understood: {'team_id', 'key_id', 'keyfile', 'topic'}
```

However, these are not only mentioned in the sample config, but clearly also used by [by the code](https://github.com/matrix-org/sygnal/blob/b784e46f3a22700efac8560d0ab0230e7c3f955f/sygnal/apnspushkin.py#L87).

**Comment by reivilibre** [comment]
Good catch. I think this was already fixed by e5b4dd1603e23a391f21576a3588a858b6351d1e (#108).

Re-open if it wasn't :).
